"""add notes to benefit_source_config

Revision ID: 1ee2f2288f60
Revises: ccc8d9df67d5
Create Date: 2026-08-03 21:16:58.572132
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1ee2f2288f60'
down_revision: Union[str, None] = 'ccc8d9df67d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefit_source_config', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benefit_source_config', 'notes')
    # ### end Alembic commands ###
