"""catalog_feature_squash

Revision ID: bf4de24769a5
Revises: 20260719_0001
Create Date: 2026-08-06 19:15:07.808563
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf4de24769a5'
down_revision: Union[str, None] = '20260719_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_source_config',
    sa.Column('source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('card_name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=128), nullable=False),
    sa.Column('annual_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_card_source_config')),
    sa.UniqueConstraint('slug', name='uq_card_source_config_slug'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_uca1400_ai_ci'
    )
    op.create_table('benefit_source_config',
    sa.Column('benefit_source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('cycle_type', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('default_amount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_overrides', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("category is null or category in ('dining', 'travel', 'others')", name=op.f('ck_benefit_source_config_category')),
    sa.CheckConstraint("cycle_type in ('monthly', 'quarterly', 'semiannual', 'annual', 'membership_year', 'anniversary', 'cert', 'multi_year')", name=op.f('ck_benefit_source_config_cycle_type')),
    sa.CheckConstraint("unit is null or unit in ('usd_credit', 'miles', 'cert', 'spend_to_goal_usd', 'event')", name=op.f('ck_benefit_source_config_unit')),
    sa.CheckConstraint('default_amount_total >= 0', name=op.f('ck_benefit_source_config_default_amount_total_nonnegative')),
    sa.ForeignKeyConstraint(['source_id'], ['card_source_config.source_id'], name=op.f('fk_benefit_source_config_source_id_card_source_config'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('benefit_source_id', name=op.f('pk_benefit_source_config')),
    sa.UniqueConstraint('source_id', 'normalized_name', name='uq_benefit_source_config_source_name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_uca1400_ai_ci'
    )
    op.create_index('ix_benefit_source_config_source_id', 'benefit_source_config', ['source_id'], unique=False)
    op.add_column('benefit_definitions', sa.Column('amount_overrides', sa.JSON(), nullable=True))
    op.add_column('benefit_definitions', sa.Column('category', sa.String(length=128), nullable=True))
    op.add_column('card_master', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_card_master_source_id_card_source_config'), 'card_master', 'card_source_config', ['source_id'], ['source_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
    op.drop_constraint('unit', 'benefit_definitions', type_='check')
    op.create_check_constraint('unit', 'benefit_definitions', "unit is null or unit in ('usd_credit', 'miles', 'cert', 'spend_to_goal_usd', 'event')")
    op.create_check_constraint('category', 'benefit_definitions', "category is null or category in ('dining', 'travel', 'others')")


def downgrade() -> None:
    op.drop_constraint('category', 'benefit_definitions', type_='check')
    op.drop_constraint('unit', 'benefit_definitions', type_='check')
    op.create_check_constraint('unit', 'benefit_definitions', "unit is null or unit in ('usd_credit', 'miles', 'cert', 'spend_to_goal_usd')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_card_master_source_id_card_source_config'), 'card_master', type_='foreignkey')
    op.drop_column('card_master', 'source_id')
    op.drop_column('benefit_definitions', 'category')
    op.drop_column('benefit_definitions', 'amount_overrides')
    op.drop_index('ix_benefit_source_config_source_id', table_name='benefit_source_config')
    op.drop_table('benefit_source_config')
    op.drop_table('card_source_config')
    # ### end Alembic commands ###
