"""add benefit_category

Revision ID: c5848f65dd25
Revises: 1ee2f2288f60
Create Date: 2026-08-06 19:07:04.833245
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c5848f65dd25'
down_revision: Union[str, None] = '1ee2f2288f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefit_definitions', sa.Column('category', sa.String(length=128), nullable=True))
    op.add_column('benefit_source_config', sa.Column('category', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###
    op.create_check_constraint('ck_benefit_definitions_category', 'benefit_definitions', "category is null or category in ('dining', 'travel', 'others')")
    op.create_check_constraint('ck_benefit_source_config_category', 'benefit_source_config', "category is null or category in ('dining', 'travel', 'others')")


def downgrade() -> None:
    op.drop_constraint('ck_benefit_source_config_category', 'benefit_source_config', type_='check')
    op.drop_constraint('ck_benefit_definitions_category', 'benefit_definitions', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benefit_source_config', 'category')
    op.drop_column('benefit_definitions', 'category')
    # ### end Alembic commands ###
