"""add amount_overrides

Revision ID: f53764c4ad37
Revises: 20260719_0001
Create Date: 2026-07-29 20:34:38.167858
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f53764c4ad37'
down_revision: Union[str, None] = '20260719_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefit_definitions', sa.Column('amount_overrides', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

    # Data Migration
    op.execute("""
        UPDATE benefit_definitions bd
        JOIN card_master cm ON bd.card_id = cm.card_id
        SET bd.amount_overrides = '{"11": 25.0, "12": 25.0}'
        WHERE cm.slug LIKE 'amex-platinum%' AND bd.normalized_name = 'uber cash'
    """)
    op.execute("""
        UPDATE benefit_definitions bd
        JOIN card_master cm ON bd.card_id = cm.card_id
        SET bd.amount_overrides = '{"12": 12.0}'
        WHERE cm.slug LIKE 'chase-united-business%' AND bd.normalized_name = 'rideshare credit'
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benefit_definitions', 'amount_overrides')
    # ### end Alembic commands ###
